config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: %i[index show new create] do
    resources :doses, only: %i[show new create]
  end
  resources :doses, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
end

app/models/dose.rb
class Dose < ApplicationRecord
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
  belongs_to :cocktail
  belongs_to :ingredient
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses, dependent: :restrict_with_error
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = @cocktail.doses.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = @cocktail.doses.new(dose_params)
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/create.html.erb
<h1>Cocktails#create</h1>
<p>Find me in app/views/cocktails/create.html.erb</p>

app/views/cocktails/index.html.erb
<h1>List of Cocktails</h1>
<ul>
<% @cocktails.each do |cocktail|%>
 <li><%=  link_to cocktail.name, cocktail_path(cocktail) %></li>
<% end %>
</ul>
<%= link_to "New Cocktail", new_cocktail_path, class: 'btn btn-primary m-5' %>

app/views/cocktails/new.html.erb
<div class="container">
  <h1>New Cocktail</h1>
  <%= simple_form_for @cocktail do |f| %>
    <%= f.input :name %>
    <%= f.submit "Add a Cocktail", class: "btn btn-primary" %>
    <%= link_to 'Home', cocktails_path, class: "btn btn-primary" %>
  <% end %>
</div>

<p>Find me in app/views/cocktails/new.html.erb</p>

app/views/cocktails/show.html.erb
<h1>Cocktails Show</h1>
<div class="container">

  <h1><%= @cocktail.name %></h1>
  <%= link_to "Back to all cocktails", cocktails_path %>

  <div class="row">
    <div class="col-sm-12 col-md-6">
      <h3>Recipe</h3>
      <table class="table table-bordered">
        <tbody>
          <thead>
            <th>Ingredient</th>
            <th>Description</th>
            <th>Action</th>
          </thead>
          <% @cocktail.doses.each do |dose| %>
            <tr>
              <td><%= dose.ingredient.name %></td>
              <td><%= dose.description %></td>
              <td>
                <%= link_to dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } do %>
                  <i class="fa fa-trash destroy_dose"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-sm-12 col-md-6">
      <%= render "doses/new", cocktail: @cocktail, dose: @dose %>
    </div>
  </div>
</div>
<p>Find me in app/views/cocktails/show.html.erb</p>

app/views/doses/_new.html.erb
<h3>Add a new dose</h3>
<div class="container">
  <h1><%= @cocktail.name %> New Dose</h1>
  <%= simple_form_for [@cocktail, @dose] do |f| %>
    <%= f.input :description %>
    <%= f.association :ingredient %>
    <%= f.submit "Add a Dose", class: "btn btn-primary"  %>
    <%= link_to 'Back', cocktail_path(@cocktail), class: "btn btn-primary"  %>
  <% end %>
</div>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<%= render "doses/new", cocktail: @cocktail, dose: @dose %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <%= javascript_include_tag "application" %>
     <%= javascript_pack_tag "application" %>
      <%= yield %>
  </body>
</html>